##
# travis configuration for oZone
##

language: cpp
sudo: required
dist: trusty
compiler: gcc

notifications:
  slack: ozonesecurity:c3kGxR60pP42b9Kr91QPtJQU
  on_success: never
  on_failure: always

branches:
  only: master

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - nodejs-legacy
      - npm
      - build-essential
      - make
      - git
      - vim
      - cmake
      - libass-dev
      - libfreetype6-dev
      - libjpeg-dev
      - libjpeg8
      - libtheora-dev
      - libtool
      - libvorbis-dev
      - pkg-config
      - texinfo
      - yasm
      - zlib1g-dev
      - libopenblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - g++-5
      - gcc-5

cache:
    directories:
      - externals/ffmpeg

install:
      - cd externals/ffmpeg
      - ./configure --enable-shared
      - make -j `grep processor /proc/cpuinfo|wc -l` 
      - sudo make install 
      - sudo make install-libs
      - cd ../dlib
      - mkdir -p build
      - cd build
      - cmake ..
      - sudo make install 

script:
      - export CXX="g++-5" CC="gcc-5"
      - cd $TRAVIS_BUILD_DIR/server
      - cmake -DOZ_EXAMPLES=ON .
      - make
      - sudo make install

